name: Concurrency
on: [push] # triggers
concurrency:
  # this workflow should be triggered for any branch only once
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # Existing will be cancelled and latest will run
jobs: 
  hello:
    runs-on: ubuntu-latest # Linux OS. We can have windows or MAC
    steps: # stages
      - name: step1
        run: sleep 20  